name: Block PRs stacked on dev

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]
    branches: 
      - 'dev'

permissions:
  pull-requests: read
  contents: read

jobs:
  block-stacked-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Block Stacked PRs
        if: github.base_ref != 'dev'
        run: |
          echo "::error::Stacked PRs are disabled in this repository. Target branch must be 'dev'."
          exit 1
        
